image: node:lts-slim

stages:
  - build

get-lspml:
  image: alpine:latest
  stage: build
  script:
    - wget https://github.com/DrWursterich/lspml/releases/latest/download/lspml_x86 -O ./resources/lspml_x86
    - chmod a+x ./resources/lspml_x86

build-vscode-extension:
  stage: build
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  needs:
    - get-lspml
  script:
    - ./node_modules/.bin/vsce pack --out ./spml-vscode.vsix
  artifacts:
    paths:
      - spml-vscode.vsix
    expire_in: "30 days"
    expose_as: "vscode-extension"