image: node:lts-slim

default:
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

stages:
  - build

build-lspml:
  stage: build
  image: rust:latest
  script:
    - git clone https://github.com/DrWursterich/lspml.git
    - cargo build --manifest-path ./lspml/Cargo.toml --release
    - cp lspml/target/release/lspml ./resources/lspml

build:
  stage: build
  needs:
    - build-lspml
  script:
    - ./node_modules/.bin/vsce pack --out ./spml-vscode.vsix
  artifacts:
    paths:
      - spml-vscode.vsix
    expire_in: "30 days"
    expose_as: "vscode-extension"