image: node:lts-slim

default:
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

stages:
  - build

build:
  stage: build
  script:
    - ./node_modules/.bin/vsce pack --out ./dist
  artifacts:
    paths:
      - dist/*.vsix
    expire_in: "30 days"
    expose_as: "extension-vsix"