name: Integrate

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/_quality.yaml
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
  package:
    name: Package
    needs: [build]
    uses: ./.github/workflows/_package.yaml